### ISSUE TITLE
Mobile browsers support.

### ISSUE THREAD

**Issue by NikolayShubenkovProgSchool** [mraid/webtester#25]
Hello. Could you please answer, can I test mraid creatives with mobile safari on iOS device?

**Comment by ncarver** [comment]
Nik, I think you are asking if the webtester will allow you to test on an iPad or iPhone. Its possible, but I would not suggest doing it. Mostly because the setup/logging is in one window and the viewer is in another viewer. That two-window approach works well on a laptop/desktop, but not on single-window devices like mobile.
-Nathan
